POST http://www.useragentstring.com  HTTP1.1
Content-Type: application/x-www-form-urlencoded
Content-Length: 140

uas=Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/73.0.3683.86%20Safari/537.36
